spring: 
  datasource: 
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      url: jdbc:mysql://localhost:3306/et?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  thymeleaf: 
    prefix: classpath:/templates/
    cache: false
  servlet:
#配置文件传输
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 1000MB
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.et.pro*
  global-config:
    #刷新mapper 调试神器
    db-config: 
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  #端口号
  port: 8080
  #项目名，如果不设定，默认是 /

